export const APP_NAME = 'WorldlyEats'
export const REACT_APP_HOST= 'http://localhost:8080'
export const REACT_APP_API= 'http://localhost:8080/api'
export const GITHUB_LINK = 'https://github.com/pgorecky'
export const LINKEDIN_LINK = 'https://linkedin.com/'
export const EMAIL_ADDRESS = 'patryk.gorecky@gmail.com'

export const LANDING_PAGE = '/'
export const SIGN_IN_PAGE = '/signin'
export const SIGN_UP_PAGE = '/signup'
export const TODO_PAGE = '/todo'
export const PROFILE_PAGE = '/profile/:id'
export const MY_PROFILE_PAGE = '/profile/me'
export const MEAL_PAGE = '/meals/:id'
export const ADD_MEAL_PAGE = '/meals/add'